---
title: "Notebook: Long running / queued chunks"
---

```{r}
# load libraries
library(dygraphs)
library(leaflet)

# import cars data
source("import.R")
cars <- import_data("cars.csv")
cars <- cars[order(cars$mpg),] 
cars <- head(cars, n = 15)

# import cities data
cities <- readr::read_csv("cities.csv")
```



## dygraphs

https://github.com/rstudio/dygraphs

Dygraphs provides rich facilities for charting time-series data in R and includes support for many interactive features including series/point highlighting, zooming, and panning.

```{r}
library(dygraphs)
dygraph(nhtemp, main = "New Haven Temperatures") %>% 
  dyRangeSelector(dateWindow = c("1920-01-01", "1960-01-01"))
```

## Leaflet

Leaflet is a JavaScript library for creating dynamic maps that support panning and zooming along with various annotations like markers, polygons, and popups.

```{r, message=FALSE, warning=FALSE}
leaflet(cities) %>% addTiles() %>%
  addCircles(lng = ~Long, lat = ~Lat, weight = 1,
    radius = ~sqrt(Pop) * 30, popup = ~City
  )
```


